// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDao5Q-z3lE64SsDjt2JKYdCWS7n5UMciY',
    appId: '1:845339002655:web:158a0dc06f8a4eba75d22a',
    messagingSenderId: '845339002655',
    projectId: 'hostel-manager-d0123a',
    authDomain: 'hostel-manager-d0123a.firebaseapp.com',
    databaseURL: 'https://hostel-manager-d0123a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hostel-manager-d0123a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeEYq4Gr_kjxqi2N4aG7FQs-AeTabUsTw',
    appId: '1:845339002655:android:2fae04e1bf53759075d22a',
    messagingSenderId: '845339002655',
    projectId: 'hostel-manager-d0123a',
    databaseURL: 'https://hostel-manager-d0123a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hostel-manager-d0123a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBybIm1eDLY6t_wHzmKG5LN-BXUtXYZJLo',
    appId: '1:845339002655:ios:fbc4d2c07aa801b875d22a',
    messagingSenderId: '845339002655',
    projectId: 'hostel-manager-d0123a',
    databaseURL: 'https://hostel-manager-d0123a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hostel-manager-d0123a.firebasestorage.app',
    iosBundleId: 'com.example.hostelManager',
  );
}
